"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import "./styles.css";

const configs = {
  "bantuan-pr": { kicker: "BANTUAN PR", title: "Pahami langkahnya,\nbukan sekadar jawabannya.", subtitle: "Tulis soal atau unggah foto. Tutor akan memberi petunjuk bertahap sesuai jenjangmu.", icon: "⌁", color: "lilac" },
  perpustakaan: { kicker: "PERPUSTAKAAN DIGITAL", title: "Temukan sumber belajar\nyang terpercaya.", subtitle: "Cari buku paket, buku cerita, dan materi dari sumber resmi Kemendikbud.", icon: "▣", color: "peach" },
  diskusi: { kicker: "RUANG DISKUSI", title: "Belajar lebih seru\nbersama teman.", subtitle: "Tanya, berbagi, dan berdiskusi dalam ruang yang aman sesuai jenjang.", icon: "◌", color: "sky" },
  tugas: { kicker: "TUGAS & PENILAIAN", title: "Satu tempat untuk\nsemua tanggung jawabmu.", subtitle: "Lihat tenggat, kumpulkan jawaban, dan pantau umpan balik dari guru.", icon: "✓", color: "mint" },
  "tutor-ai": { kicker: "TUTOR AI PRIBADI", title: "Teman belajar yang\nselalu siap membantu.", subtitle: "Penjelasan personal berdasarkan jenjang, mapel, dan progres belajarmu.", icon: "✦", color: "green" },
  akun: { kicker: "AKUN & KEAMANAN", title: "Kamu memegang kendali\natas akunmu.", subtitle: "Kelola profil, preferensi, dan perlindungan data dengan aman.", icon: "⚙", color: "navy" },
};

function Shell({ children, config }) {
  const items = [["/", "⌂", "Beranda"], ["/latihan-soal", "✎", "Latihan Soal"], ["/bantuan-pr", "?", "Bantuan PR"], ["/perpustakaan", "▣", "Perpustakaan"], ["/diskusi", "◌", "Diskusi"], ["/tugas", "✓", "Tugas"], ["/tutor-ai", "✦", "Tutor AI"]];
  return <main className="feature-shell"><aside className="feature-sidebar"><Link href="/" className="feature-brand"><span>✦</span><strong>Sekolah<br />Cerdas</strong></Link><div className="feature-profile"><span>NP</span><div><strong>Nadia Pratama</strong><small>SMA · Kelas 11</small></div></div><nav>{items.map(([href, icon, label]) => <Link href={href} key={label} className={config.kicker.includes(label.toUpperCase()) ? "active" : ""}><i>{icon}</i>{label}{label === "Tugas" && <b>2</b>}</Link>)}</nav><div className="feature-side-bottom"><Link href="/akun">⚙ &nbsp; Pengaturan akun</Link><small>♢ &nbsp; Ruang aman untuk belajar</small></div></aside><section className="feature-content"><header className="feature-topbar"><Link href="/" className="crumb">Sekolah Cerdas <span>/</span> {config.kicker.toLowerCase()}</Link><div className="feature-actions">⌕ &nbsp;&nbsp; ♢ <span>NP</span></div></header>{children}</section></main>;
}

function Homework({ config }) { const [messages, setMessages] = useState([]); const [text, setText] = useState(""); const send = () => { if (!text.trim()) return; setMessages((old) => [...old, { role: "user", text }, { role: "ai", text: "Mari kita pecah soal ini menjadi langkah kecil. Apa informasi yang sudah kamu ketahui dari soal tersebut?" }]); setText(""); }; return <Shell config={config}><div className="feature-body"><FeatureHero config={config} /><div className="split-panels"><div className="chat-panel"><div className="panel-head"><div><span className="panel-icon lilac">⌁</span><div><strong>Sesi bantuan baru</strong><small>Petunjuk bertahap · SMA</small></div></div><span className="online">● Aman</span></div><div className="chat-messages"><div className="ai-bubble">Halo, Nadia! Kirim soal yang ingin kamu pahami. Aku akan membantumu menemukan jawabannya sendiri, langkah demi langkah. <small>Baru saja</small></div>{messages.map((message, index) => <div className={message.role === "user" ? "user-bubble" : "ai-bubble"} key={index}>{message.text}<small>Baru saja</small></div>)}</div><div className="chat-input"><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === "Enter" && send()} placeholder="Tulis pertanyaan atau tempel soal di sini..." /><button onClick={send}>↑</button></div></div><div className="side-card"><p className="mini-kicker">RIWAYAT BANTUAN</p>{["Persamaan kuadrat", "Hukum Newton", "Teks eksplanasi"].map((x, i) => <div className="history-row" key={x}><span>{i === 0 ? "◫" : "◌"}</span><div><strong>{x}</strong><small>{i + 1} hari lalu</small></div>›</div>)}<button className="outline-button">Lihat semua riwayat</button></div></div></div></Shell> }

function Library({ config }) { const [query, setQuery] = useState(""); const [saved, setSaved] = useState([]); const books = [{ title: "Matematika untuk SMA/MA Kelas XI", author: "Kementerian Pendidikan", meta: "Matematika · SMA", type: "Buku paket" }, { title: "Fisika untuk SMA Kelas XI", author: "Kementerian Pendidikan", meta: "Fisika · SMA", type: "Buku paket" }, { title: "Bumi dan Antariksa", author: "Pusat Perbukuan", meta: "Sains · SMP", type: "Materi" }, { title: "Cerita Rakyat Nusantara", author: "Badan Bahasa", meta: "Bahasa Indonesia · SD", type: "Buku cerita" }]; const shown = books.filter((b) => `${b.title} ${b.meta}`.toLowerCase().includes(query.toLowerCase())); return <Shell config={config}><div className="feature-body"><FeatureHero config={config} /><div className="library-toolbar"><div className="large-search">⌕ <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari judul, jenjang, atau mata pelajaran..." /></div><button className="filter-button">☷ Filter</button></div><div className="library-grid">{shown.map((book, index) => <div className="book-card" key={book.title}><div className={`book-cover cover-${index}`}><span>{book.type}</span><strong>{book.title.split(" ").slice(0, 2).join(" ")}</strong></div><div className="book-info"><span className="book-type">{book.type}</span><h3>{book.title}</h3><p>{book.author}</p><small>{book.meta}</small><div><button className="source-button">Buka sumber resmi ↗</button><button className={`save-button ${saved.includes(index) ? "saved" : ""}`} onClick={() => setSaved((old) => old.includes(index) ? old.filter((x) => x !== index) : [...old, index])}>{saved.includes(index) ? "♥" : "♡"}</button></div></div></div>)}</div></div></Shell> }

function Forum({ config }) { const [tab, setTab] = useState("Sejenjang"); const [liked, setLiked] = useState([]); const threads = [{ title: "Bagaimana cara cepat memahami integral substitusi?", author: "Raka · SMA 11", replies: 12, category: "Matematika" }, { title: "Rekomendasi cara belajar sebelum ujian Fisika", author: "Salsa · SMA 10", replies: 8, category: "Tips belajar" }, { title: "Diskusi: energi terbarukan di Indonesia", author: "Dimas · SMA 11", replies: 24, category: "Sains" }]; return <Shell config={config}><div className="feature-body"><FeatureHero config={config} /><div className="forum-tabs">{["Sejenjang", "Forum terbuka", "Forum sekolah"].map((x) => <button className={tab === x ? "selected" : ""} key={x} onClick={() => setTab(x)}>{x}</button>)}<button className="new-topic">＋ Buat topik</button></div><div className="forum-layout"><div className="thread-list">{threads.map((thread, index) => <div className="thread-row" key={thread.title}><div className="thread-avatar">{["RK", "SL", "DM"][index]}</div><div className="thread-copy"><span>{thread.category} · 2 jam lalu</span><h3>{thread.title}</h3><small>{thread.author}</small></div><div className="thread-meta"><strong>{thread.replies}</strong><small>balasan</small><button onClick={() => setLiked((old) => old.includes(index) ? old.filter((x) => x !== index) : [...old, index])}>{liked.includes(index) ? "♥" : "♡"}</button></div></div>)}</div><div className="moderation-card"><span className="panel-icon sky">♢</span><h3>Ruang aman bersama</h3><p>Jaga diskusi tetap sopan. Semua konten dipantau dan bisa dilaporkan jika tidak sesuai.</p><button className="text-link">Pelajari panduan komunitas →</button></div></div></div></Shell> }

function Assignments({ config }) { const [submitted, setSubmitted] = useState([]); const tasks = [{ title: "Latihan soal Hukum Newton", subject: "Fisika", due: "Besok, 23:59", status: "Belum dikerjakan" }, { title: "Esai: Dampak teknologi", subject: "Bahasa Indonesia", due: "20 Agustus 2026", status: "Belum dikerjakan" }, { title: "Rangkuman Bab 4", subject: "Matematika", due: "Selesai", status: "Dinilai · 88" }]; return <Shell config={config}><div className="feature-body"><FeatureHero config={config} /><div className="task-summary"><div><small>AKTIF</small><strong>2</strong><span>tugas menunggu</span></div><div><small>SELESAI</small><strong>8</strong><span>tugas semester ini</span></div><div><small>NILAI RATA-RATA</small><strong>86</strong><span>dari 100</span></div></div><div className="assignment-card"><div className="panel-head"><div><p className="mini-kicker">DAFTAR TUGAS</p><h2>Tugasmu</h2></div><button className="filter-button">Semua status⌄</button></div>{tasks.map((task, index) => <div className="assignment-row" key={task.title}><span className={`task-symbol ${index === 0 ? "urgent" : ""}`}>{index === 2 ? "✓" : "!"}</span><div><strong>{task.title}</strong><small>{task.subject} · {task.due}</small></div><span className={task.status.includes("Dinilai") ? "graded" : submitted.includes(index) ? "submitted" : "pending"}>{submitted.includes(index) ? "Dikumpulkan" : task.status}</span>{index !== 2 && <button className="submit-button" onClick={() => setSubmitted((old) => [...old, index])}>{submitted.includes(index) ? "Terkirim" : "Kumpulkan"}</button>}</div>)}</div></div></Shell> }

function Tutor({ config }) { const [messages, setMessages] = useState([{ role: "ai", text: "Halo, Nadia! Aku siap membantumu belajar. Mau membahas topik apa hari ini?" }]); const [text, setText] = useState(""); const send = () => { if (!text.trim()) return; setMessages((old) => [...old, { role: "user", text }, { role: "ai", text: "Pertanyaan yang bagus. Mari kita mulai dari konsep dasarnya, lalu kita hubungkan dengan contoh yang dekat dengan kehidupan sehari-hari." }]); setText(""); }; return <Shell config={config}><div className="feature-body"><FeatureHero config={config} /><div className="tutor-layout"><div className="tutor-chat"><div className="tutor-header"><span className="tutor-avatar">✦</span><div><strong>Cerdas, Tutor AI</strong><small>● Online · Sesuai jenjang SMA</small></div><button>Minta bantuan guru</button></div><div className="tutor-messages">{messages.map((m, i) => <div className={m.role === "user" ? "user-bubble" : "ai-bubble"} key={i}>{m.text}<small>Baru saja</small></div>)}</div><div className="chat-input"><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === "Enter" && send()} placeholder="Tanyakan apa saja tentang pelajaran..." /><button onClick={send}>↑</button></div></div><div className="recommend-card"><p className="mini-kicker">REKOMENDASI UNTUKMU</p><h3>Karena progresmu di Fisika</h3>{["Usaha dan energi", "Gerak parabola", "Latihan Hukum Newton"].map((x) => <button key={x}><span>✦</span><div><strong>{x}</strong><small>Materi rekomendasi</small></div>›</button>)}</div></div></div></Shell> }

function Account({ config }) { const [saved, setSaved] = useState(false); return <Shell config={config}><div className="feature-body"><FeatureHero config={config} /><div className="account-grid"><div className="account-card"><div className="account-head"><span className="big-avatar">NP</span><div><h2>Nadia Pratama</h2><p>nadia.pratama@email.com</p><span className="role-label">Siswa · SMA</span></div><button className="outline-button">Ubah foto</button></div>{[["Nama lengkap", "Nadia Pratama"], ["Sekolah", "SMA Negeri 4 Bandung"], ["Kelas", "XI IPA"], ["Mata pelajaran favorit", "Fisika, Matematika"]].map(([label, value]) => <label key={label}>{label}<input defaultValue={value} /></label>)}<button className="primary-button" onClick={() => setSaved(true)}>{saved ? "✓ Perubahan tersimpan" : "Simpan perubahan"}</button></div><div className="security-card"><p className="mini-kicker">PERLINDUNGAN AKUN</p>{[["♢", "Data terlindungi", "Informasi siswa tidak ditampilkan ke publik"], ["✓", "Persetujuan wali aktif", "Akunmu memiliki perlindungan pengguna anak"], ["◷", "Aktivitas terbaru", "Login terakhir hari ini, 08:42"]].map(([icon, title, text]) => <div className="security-row" key={title}><span>{icon}</span><div><strong>{title}</strong><small>{text}</small></div></div>)}<button className="text-link">Buka catatan aktivitas admin →</button></div></div></div></Shell> }

function FeatureHero({ config }) { return <div className="feature-hero"><div><p className="feature-kicker">{config.kicker}</p><h1>{config.title.split("\n").map((line, i) => <span key={i}>{line}<br /></span>)}</h1><p>{config.subtitle}</p></div><span className={`hero-icon ${config.color}`}>{config.icon}</span></div> }

export default function FeaturePage({ params }) { const config = configs[params.feature] || configs["bantuan-pr"]; if (params.feature === "bantuan-pr") return <Homework config={config} />; if (params.feature === "perpustakaan") return <Library config={config} />; if (params.feature === "diskusi") return <Forum config={config} />; if (params.feature === "tugas") return <Assignments config={config} />; if (params.feature === "tutor-ai") return <Tutor config={config} />; return <Account config={config} />; }
