"use client";

import Link from "next/link";
import { useState } from "react";
import "../auth.css";

export default function RegisterPage() { const [form, setForm] = useState({ fullName: "", email: "", password: "", role: "student" }); const [message, setMessage] = useState(""); const change = (key, value) => setForm((old) => ({ ...old, [key]: value })); async function register(event) { event.preventDefault(); setMessage("Membuat akun..."); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); setMessage(response.ok ? "Akun berhasil dibuat. Silakan masuk." : data.error); } return <AuthShell><p className="auth-kicker">MULAI PERJALANANMU</p><h1>Buat akun<br /><em>belajarmu.</em></h1><p className="auth-subtitle">Satu akun untuk semua kebutuhan belajar.</p><form onSubmit={register}><label>Nama lengkap<input value={form.fullName} onChange={(e) => change("fullName", e.target.value)} placeholder="Nama kamu" required /></label><label>Daftar sebagai<select value={form.role} onChange={(e) => change("role", e.target.value)}><option value="student">Siswa</option><option value="teacher">Guru</option><option value="school_admin">Admin sekolah</option></select></label><label>Email<input type="email" value={form.email} onChange={(e) => change("email", e.target.value)} placeholder="nama@email.com" required /></label><label>Kata sandi<input type="password" value={form.password} onChange={(e) => change("password", e.target.value)} placeholder="Minimal 8 karakter" minLength="8" required /></label><label className="consent"><input type="checkbox" required /> Saya menyetujui ketentuan dan perlindungan data pengguna.</label><button className="auth-button">Buat akun <span>→</span></button>{message && <p className="auth-message">{message}</p>}</form><p className="auth-switch">Sudah punya akun? <Link href="/masuk">Masuk</Link></p></AuthShell>; }

function AuthShell({ children }) { return <main className="auth-page"><div className="auth-art"><Link href="/" className="auth-brand"><span>✦</span>Sekolah Cerdas</Link><div><p className="auth-art-kicker">RUANG AMAN UNTUK TUMBUH</p><h2>Setiap pertanyaan<br />adalah <em>awal</em> baru.</h2><p>Belajar dengan sumber terpercaya, bantuan yang membimbing, dan komunitas yang saling menjaga.</p></div><small>♢ Data dan privasi kamu kami lindungi.</small></div><section className="auth-card">{children}</section></main>; }
